import type {
  BookingWidgetTheme,
  BookingWidgetVariant,
} from "./booking-widget.types";

export const bookingWidgetThemes: Record<
  BookingWidgetVariant,
  BookingWidgetTheme
> = {
  glass: {
    root: "booking-widget--glass",
    panel: "bg-white/45 backdrop-blur-2xl shadow-hero-card",
    brandPanel: "border-white/70 text-forest",
    contentPanel: "border-white/70 text-forest",
    heading: "text-forest",
    body: "text-coffee",
    muted: "text-coffee/65",
    serviceMeta: "text-forest-soft",
    brandSubtitle: "text-warm",
    contentBlob: "from-forest-soft to-forest",
    showContentBlob: true,
    border: "border-white/70",
    primaryButton: "bg-forest text-canvas hover:bg-forest-hover",
    secondaryButton: "border-forest/35 text-forest hover:bg-forest/8",
    slot: "border-forest/18 text-forest hover:border-sage hover:bg-meadow/25",
    selectedSlot: "border-sage bg-sage text-surface",
    disabledSlot: "border-coffee/10 text-coffee/35",
    switchTrack: "border-forest/14 bg-white/55",
    switchActive: "bg-sage text-surface",
    calendarSelectedDay: "bg-sage text-surface",
    calendarAvailableDay: "text-forest hover:bg-meadow/35",
    calendarDisabledDay: "text-coffee/25",
  },
  light: {
    root: "booking-widget--light",
    panel: "bg-surface shadow-hero-card",
    brandPanel: "border-forest/10 bg-surface/75 text-forest",
    contentPanel: "border-forest/10 text-forest",
    heading: "text-forest",
    body: "text-coffee",
    muted: "text-coffee/65",
    serviceMeta: "text-warm",
    brandSubtitle: "text-warm",
    contentBlob: "from-warm to-warm-hover",
    showContentBlob: false,
    border: "border-forest/10",
    primaryButton: "bg-warm text-surface hover:bg-warm-hover",
    secondaryButton: "border-warm/70 text-coffee hover:bg-warm/10",
    slot: "border-coffee/16 text-coffee hover:border-warm hover:bg-warm/10",
    selectedSlot: "border-warm bg-warm text-surface",
    disabledSlot: "border-coffee/10 text-coffee/35",
    switchTrack: "border-forest/12 bg-canvas",
    switchActive: "bg-sage text-surface",
    calendarSelectedDay: "bg-sage text-surface",
    calendarAvailableDay: "text-forest hover:bg-meadow/35",
    calendarDisabledDay: "text-coffee/25",
  },
  dark: {
    root: "booking-widget--dark",
    panel: "bg-forest shadow-hero-card",
    brandPanel: "border-white/20 text-surface",
    contentPanel: "border-white/20 text-surface",
    heading: "text-surface",
    body: "text-surface",
    muted: "text-surface/68",
    serviceMeta: "text-meadow",
    brandSubtitle: "text-warm",
    contentBlob: "from-meadow to-sage",
    showContentBlob: false,
    border: "border-white/16",
    primaryButton: "bg-meadow text-forest hover:bg-meadow-hover",
    secondaryButton: "border-warm/75 text-surface hover:bg-warm/15",
    slot: "border-white/30 text-surface hover:border-meadow hover:bg-white/10",
    selectedSlot: "border-meadow bg-meadow text-forest",
    disabledSlot: "border-white/10 text-white/35",
    switchTrack: "border-white/30 bg-black/10",
    switchActive: "bg-meadow text-forest",
    calendarSelectedDay: "bg-meadow text-forest",
    calendarAvailableDay: "text-surface hover:bg-white/10",
    calendarDisabledDay: "text-white/30",
  },
};
