"""20260806_0020_add_content_review_assignments

Revision ID: 359e86bf2cb4
Revises: b6f366950a46
Create Date: 2026-08-06 02:29:49.643734

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "359e86bf2cb4"
down_revision: str | Sequence[str] | None = "b6f366950a46"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_review_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "capability",
            sa.Enum(
                "clinical",
                "legal",
                "business",
                name="approvalcapability",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "email_notifications", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_content_review_assignments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["internal_users.id"],
            name=op.f("fk_content_review_assignments_user_id_internal_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_review_assignments")),
        sa.UniqueConstraint(
            "organization_id", "user_id", "capability", name="uq_content_review_assignment"
        ),
    )
    op.create_index(
        op.f("ix_content_review_assignments_organization_id"),
        "content_review_assignments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_review_assignments_user_id"),
        "content_review_assignments",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_content_review_assignments_user_id"), table_name="content_review_assignments"
    )
    op.drop_index(
        op.f("ix_content_review_assignments_organization_id"),
        table_name="content_review_assignments",
    )
    op.drop_table("content_review_assignments")
    # ### end Alembic commands ###
