"""20260806_0021_add_notification_outbox

Revision ID: 3bb47763bb91
Revises: 359e86bf2cb4
Create Date: 2026-08-06 03:03:34.709887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb47763bb91'
down_revision: Union[str, Sequence[str], None] = '359e86bf2cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_type', sa.String(length=40), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aggregate_id'], ['content_revisions.id'], name=op.f('fk_notification_outbox_aggregate_id_content_revisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notification_outbox_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['internal_users.id'], name=op.f('fk_notification_outbox_recipient_user_id_internal_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_outbox'))
    )
    op.create_index(op.f('ix_notification_outbox_organization_id'), 'notification_outbox', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_outbox_organization_id'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    # ### end Alembic commands ###
