"""20260805_0018_add_content_submit_idempotency

Revision ID: 9d428d84862d
Revises: 20260803_0017
Create Date: 2026-08-05 19:54:42.511585

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d428d84862d"
down_revision: str | Sequence[str] | None = "20260803_0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_submit_idempotency",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["content_revisions.id"],
            name=op.f("fk_content_submit_idempotency_revision_id_content_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_submit_idempotency")),
        sa.UniqueConstraint("revision_id", "idempotency_key", name="uq_content_submit_idempotency"),
    )
    op.create_index(
        op.f("ix_content_submit_idempotency_revision_id"),
        "content_submit_idempotency",
        ["revision_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_content_submit_idempotency_revision_id"), table_name="content_submit_idempotency"
    )
    op.drop_table("content_submit_idempotency")
    # ### end Alembic commands ###
