"""20260805_0019_add_revision_lineage

Revision ID: b6f366950a46
Revises: 9d428d84862d
Create Date: 2026-08-05 20:31:06.233676

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6f366950a46"
down_revision: str | Sequence[str] | None = "9d428d84862d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content_revisions", sa.Column("source_revision_id", sa.Uuid(), nullable=True))
    op.add_column(
        "content_revisions", sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "content_revisions", sa.Column("superseded_by_revision_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_content_revisions_source_revision_id_content_revisions"),
        "content_revisions",
        "content_revisions",
        ["source_revision_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_content_revisions_superseded_by_revision_id_content_revisions"),
        "content_revisions",
        "content_revisions",
        ["superseded_by_revision_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_content_revisions_superseded_by_revision_id_content_revisions"),
        "content_revisions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_content_revisions_source_revision_id_content_revisions"),
        "content_revisions",
        type_="foreignkey",
    )
    op.drop_column("content_revisions", "superseded_by_revision_id")
    op.drop_column("content_revisions", "superseded_at")
    op.drop_column("content_revisions", "source_revision_id")
    # ### end Alembic commands ###
